Repository sbpp/sourcebans-pp, pull requests merged in 2018-03, with the labels that each got.

#399 Updated smarty to 2.6.31
  web/includes/smarty/Smarty.class.php
  web/includes/smarty/Smarty_Compiler.class.php
  web/includes/smarty/plugins/function.math.php
Labels: Status: Help Wanted, Status: Review Needed, Status: Testing Needed, Type: Enhancement

#408 Report Player Native
  .travis.yml
  appveyor.yml
  game/addons/sourcemod/scripting/include/sourcebans.inc
  game/addons/sourcemod/scripting/sbpp_main.sp
  game/addons/sourcemod/scripting/sbpp_report.sp
  game/addons/sourcemod/translations/sbpp_report.phrases.txt
Labels: Status: Help Wanted, Status: Testing Needed, Type: Feature

#413 Add French Translate
  game/addons/sourcemod/scripting/sbpp_report.sp
  game/addons/sourcemod/translations/sourcereport.phrases.txt
Labels: Type: Enhancement
