Repository sbpp/sourcebans-pp, pull requests merged in 2019-10, with the labels that each got.

#619 Update French Translate
  game/addons/sourcemod/translations/sbpp_main.phrases.txt
Labels: t: plugin, t: translations, template: used

#614 refactor: Standardized Main Chat Prints
  game/addons/sourcemod/scripting/sbpp_main.sp
Labels: semver: patch, t: plugin, type: maintenance

#624 Fixing Public Comments checkbox in Settings
  web/pages/admin.settings.php
Labels: semver: patch, t: permission system, t: ui/ux, template: used

#626 Fix new warning on SM 1.10.
  game/addons/sourcemod/scripting/sbpp_comms.sp
Labels: semver: patch, t: plugin

#627 ci: Update builders.
  .travis.yml
  appveyor.yml
Labels: semver: N/A, type: maintenance
